### ISSUE TITLE
 Invalid port syntax error

### ISSUE THREAD

**Issue by wehappyfew** [snagles/docker-registry-manager#133]
I am trying to run the container with this config file
```
app:
  log-level: "debug"
  port: 8080

registries:
  myregistry:
    url: myregistry.azurecr.io:5000
    username: SomeUser
    password: SomePass
    refresh-rate: "5m"
```

and I get this error...

```
INFO[0000] Using config located in /var/lib/docker-registry-manager with config name config
FATA[0000] Failed to add registry (myregistry.azurecr.io:5000), invalid port: strconv.Atoi: parsing "": invalid syntax
```
