### ISSUE TITLE
SSL: "HTTPS enabled, but no key file provided" yet it has been provided and works for other services

### ISSUE THREAD

**Issue by draeath** [snagles/docker-registry-manager#139]
```
[root@registry docker-registry-manager]# git reflog
4ac06ef HEAD@{0}: clone: from https://github.com/snagles/docker-registry-manager.git

[root@registry docker-registry-manager]# git show 4ac06ef | head -n1
commit 4ac06efda418742f0f68b2e91bc70dc2ea692a1
```

My docker-compose.yml looks as-follows:

```
version: '2'

services:
  docker-registry-manager:
    container_name: docker-registry-manager
    image: snagles/docker-registry-manager
    ports:
      - "42443:42443"
    volumes:
      - ./registries.yml:/app/registries.yml
      - /certs/registry.{REDACTED}.crt:/app/ssl.crt
      - /certs/registry.{REDACTED}.key:/app/ssl.key

    environment:
      - MANAGER_PORT=42443
      - MANAGER_REGISTRIES=/app/registries.yml
      - MANAGER_LOG_LEVEL=warn
      - MANAGER_ENABLE_HTTPS=true
      - MANAGER_KEY=/app/ssl.key
      - MANAGER_CERTIFICATE=/app/ssl.crt
```

These are valid files, in that they work for other services (namely our registry). However, the container dies, emitting the following into the docker logs:

```
time="2018-02-13T19:56:49Z" level=fatal msg="HTTPS enabled, but no key file provided" file=main.go line=120 source=app
```

```
[root@registry certs]# pwd
/certs

[root@registry certs]# head -n1 registry.{REDACTED}.key; tail -n1 registry.{REDACTED}.key
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----

[root@registry certs]# head -n1 registry.{REDACTED}.crt; tail -n1 registry.{REDACTED}.crt
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
```

Is the application overly-sensitive to specific key or certificate formats? Is it expecting [PKCS#1 specifically, and PKCS#8 is incompatible?](https://stackoverflow.com/a/20065522)
