### ISSUE TITLE
Container doesn't work when enabling HTTPS

### ISSUE THREAD

**Issue by amit7itz** [snagles/docker-registry-manager#191]
Hi!
I set up the docker registry manager with HTTP worked fine, 
But when I enable the https, for some reason it just exits with error code 0 after a second. 
```
[root@registry docker-registry-manager]# docker-compose up
Starting docker-registry-manager ... done
Attaching to docker-registry-manager
docker-registry-manager    | time="2019-12-03T17:20:24Z" level=info msg="Using registries located in /app with file name registries" file=allregistries.go line=161 source=app
docker-registry-manager    | time="2019-12-03T17:20:24Z" level=info msg="Added new registry: registry" file=allregistries.go line=110 source=app
docker-registry-manager    | time="2019-12-03T17:20:24Z" level=info msg="Admin server Running on :8088" file=log.go line=610 source=beego
docker-registry-manager    | time="2019-12-03T17:20:24Z" level=info msg="https server Running on https://:8080" file=log.go line=610 source=beego
docker-registry-manager exited with code 0
```

This is the docker-compose
```
version: '2'

services:
  docker-registry-manager:
    container_name: docker-registry-manager
    image: snagles/docker-registry-manager
    ports:
      - "8080:8080"
    volumes:
      - ./registries.yml:/app/registries.yml
      - /root/certs:/app/certs

    environment:
      - MANAGER_PORT=8080
      - MANAGER_REGISTRIES=/app/registries.yml
      - MANAGER_LOG_LEVEL=debug
      - MANAGER_ENABLE_HTTPS=true
      - MANAGER_KEY=/app/certs/domain.crt
      - MANAGER_CERTIFICATE=/app/certs/domain.key
```

Help please? :)
