### ISSUE TITLE
Local registry with localhost as url

### ISSUE THREAD

**Issue by ghost** [snagles/docker-registry-manager#198]
Hello!
I am trying to test the docker registry manager with the simplest possible setup.
My registry is in a container and contactable at localhost:5000.

Here is the registries.yml:
```
registries:
  exampleRegistry:
    displayname: registry
    url: localhost
    port: 5000 # Example: 443, 8080, 5000
    #username: exampleUser
    #password: examplePassword
    refresh-rate: "5m" # Example: 60s, 5m, 1h
```

However, when I run `docker-compose up -d`, I cannot see anything at localhost:8080 on my browser.

Running `docker-compose logs -f docker-registry-manager` gives:
```Attaching to docker-registry-manager
docker-registry-manager    | time="2020-12-09T13:20:33Z" level=info msg="Using registries located in /app with file name registries" file=allregistries.go line=161 source=app
docker-registry-manager    | time="2020-12-09T13:20:33Z" level=fatal msg="Failed to create registry (localhost): Invalid scheme: " file=allregistries.go line=198 source=app
docker-registry-manager exited with code 1
```

What is wrong here?

Best regards.
