### ISSUE TITLE
standard_init_linux.go:219: exec user process caused: exec format error

### ISSUE THREAD

**Issue by G-R-A-F-F** [snagles/docker-registry-manager#199]
Hi,

I am running a registry on raspberry Pi and trying to run this container on the same pi.
Keep getting the above-noted error.
Is there anything I configured wrong?

docker-compose:
```
version: '2'

services:
  docker-registry-manager:
    container_name: docker-registry-manager
    image: snagles/docker-registry-manager
    ports:
      - "5001:8080"
    volumes:
      - ./registries.yml:/app/registries.yml
      #- ./ssl.crt:/app/ssl.crt # https certfile location
      #- ./ssl.key:/app/ssl.key # https keyfile location

    environment:
      - MANAGER_PORT=8080
      - MANAGER_REGISTRIES=/app/registries.yml
      - MANAGER_LOG_LEVEL=warn
      - MANAGER_ENABLE_HTTPS=false
      #- MANAGER_KEY=/app/ssl.crt
      #- MANAGER_CERTIFICATE=/app/ssl.key

```

registry.xml
```
registries:
  exampleRegistry:
    displayname: registry:5000
    url: http://localhost
    port: 5000 # Example: 443, 8080, 5000
    #username: exampleUser
    #password: examplePassword
    #refresh-rate: "5m" # Example: 60s, 5m, 1h
    #skip-tls-validation: true # REQUIRED for self signed certificates
    #dockerhub-integration: true # Optional - compares to dockerhub to determine if image up to date

```
